version: '3.4'

services:
  bi1helloworld:
    image: bi1helloworld
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
