version: '3.4'

services:
  bi1nodeazure:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev #Change this to prod to build the production image
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "run", "dev"]