@startuml
Interface dataobject{
  name
  {static} constructor(name: string)
  {static} all()
  + exists(): boolean
  + create(name: string): boolean
  + download(name: string): boolean
  + publish(name: string)
  + delete()
}
@enduml